apiVersion: v1
kind: ConfigMap
metadata:
  name: http-proxy-config
data:
  squid.conf: |
    # Listen port.
    http_port 3128
    
    # Allow local traffic (adjust to your network).
    acl localnet src 10.0.0.0/8     
    acl localnet src 192.168.0.0/16
    http_access allow localnet
    
    # Block the rest.
    http_access deny all
    
    # Allow CONNECT (TLS passthrough) method.
    acl SSL_ports port 443
    acl CONNECT method CONNECT
    http_access allow CONNECT SSL_ports localnet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-proxy-config
data:
  haproxy.cfg: |
    global
       log stdout format raw local0
  
    defaults
       log global
       mode tcp
       timeout connect 10s  # Connection timeout for connecting to backend servers.
       timeout client 1m    # Timeout for client inactivity.
       timeout server 1m    # Timeout for server inactivity.
    
    frontend postgresql_frontend
       bind *:5432
       mode tcp
       default_backend postgresql_backend
  
    backend postgresql_backend
       mode tcp
       balance roundrobin
       server postgresql-server <your-postgresql-server-hostname>:5432 check