apiVersion: v1
kind: ConfigMap
metadata:
  name: egress-gateway-config
data:
  squid.conf: |
    # Listen port.
    http_port 3128
    
    # Allow local traffic (adjust to your network).
    acl localnet src 10.0.0.0/8     
    acl localnet src 192.168.0.0/16
    http_access allow localnet
    
    # Block the rest.
    http_access deny all
    
    # Allow HTTPS CONNECT (TLS passthrough) method.
    acl SSL_ports port 443
    acl CONNECT method CONNECT
    http_access allow CONNECT SSL_ports localnet