apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: egress-gateway
  template:
    metadata:
      labels:
        app: egress-gateway
    spec:
      nodeSelector:
        egressGateway: "true"
      containers:
        - name: egress-gateway
          image: nginx:latest
          volumeMounts:
            - name: egress-gateway-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: egress-gateway-certificate
              mountPath: /etc/tls/certs/fullchain.pem
              subPath: fullchain.pem
            - name: egress-gateway-certificate-key
              mountPath: /etc/tls/private/privkey.pem
              subPath: privkey.pem
      volumes:
        - name: egress-gateway-config
          configMap:
            name: egress-gateway-config
        - name: egress-gateway-certificate
          configMap:
            name: egress-gateway-certificate
        - name: egress-gateway-certificate-key
          configMap:
            name: egress-gateway-certificate-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        workerNodes: "true"
      containers:
        - name: client
          image: alpine:latest
          command: ["sleep", "infinity"]
          tty: true
          env:
            - name: HTTP_PROXY
              value: "http://egress-gateway"
            - name: HTTPS_PROXY
              value: "https://egress-gateway"