apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: egress-gateway
  template:
    metadata:
      labels:
        app: egress-gateway
    spec:
      nodeSelector:
        egressGateway: "true"
      containers:
        - name: egress-gateway
          image: nginx:1.27.2
          volumeMounts:
            - name: egress-gateway-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: egress-gateway-config
          configMap:
            name: egress-gateway-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        workerNodes: "true"
      containers:
        - name: client
          image: alpine:3.20.3
          command: ["sleep", "infinity"]
          tty: true
          env:
            - name: http_proxy
              value: "http://egress-gateway"