apiVersion: v1
kind: Service
metadata:
  name: web-gateway
spec:
  selector:
    app: http-proxy
  ports:
    - protocol: TCP
      port: 3128
      targetPort: 3128
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-gateway
spec:
  selector:
    app: tcp-proxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
